---
- hosts: localhost

  become: true

  tasks:
    - name: Install add-apt repository
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: 
        name: [oracle-java8-installer, ca-certificates, oracle-java8-set-default] 
        state: latest 
        update-cache: yes

    - name: Ensure botocore and boto3 modules are installed
      become: yes
      pip:
        name:         [ "boto3", "botocore"]
        extra_args:   "--user"

    - name: Copy File from S3 bucket to EC2 instance
      become: yes
      command: "aws s3 sync s3://bridgelabz-ansible-test-bucket/demo.txt /home/ubuntu/"
